---
# tasks file for ci_runner

- name: install dnf for plugins
  dnf:
    name: 'dnf-command(copr)'
    state: latest

- name: activate copr repos
  shell: /usr/bin/dnf copr -y enable karmab/kcli

- name: install pgks
  dnf:
    name:
        - git
        - tree
        - kcli
        - libvirt
        - libvirt-daemon-driver-qemu
        - qemu-img
        - qemu-system-x86
        - qemu-system-x86-core
        - rust
        - cargo
        - docker
        - docker-compose
        - python3-docker
        - openvswitch
        - iproute
        - ansible
        - openvswitch
        - iproute
        - ansible
    state: latest

- name: start services
  service:
      name: "{{ svc }}"
      enabled: yes
      state: started
  loop:
      - "docker"
      - "openvswitch"
  loop_control:
    loop_var: svc

- name: install mask
  shell: cargo install -f --vers "0.7.1" --root /usr/local/ mask

- name: deliver flowgrind
  include_tasks: "{{ role_path }}/tasks/flowgrind.yml"

# as install is net stack disruptive
# better to be endian task
- name: provide kernel extras for netem tc 
  dnf:
    name:
        - kernel-modules-extra 
    state: latest
