##
## Copyright (c) 2019 Matthias Tafelmeier
##
## This file is part of godon
##
## godon is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## godon is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with godon. If not, see <http://www.gnu.org/licenses/>.
##
---
# tasks file for ci_runner

- name: start services
  service:
      name: "{{ svc }}"
      enabled: yes
      state: started
  loop:
      - "docker"
      - "openvswitch"
  loop_control:
    loop_var: svc

- name: install mask
  shell: cargo install -f --vers "0.11.0" --root /usr/local/ mask

- name: deliver flowgrind
  include_tasks: "{{ role_path }}/tasks/flowgrind.yml"

- name: attain kcli
  docker_image:
    source: pull
    name: karmab/kcli

# as install is net stack disruptive
# better to be endian task
- name: provide kernel extras for netem tc 
  dnf:
    name:
        - kernel-modules-extra 
    state: latest
