---

fedora31:
 type: image
 pool: image_pool

image_pool:
  type: pool
  path: /srv/

oob_net:
 type: network
 cidr: 10.0.5.0/24

micro_fedora:
  type: profile
  image: fedora31
  memory: 2048 
  numcpus: 2
  pool: image_pool 

source_vm:
  profile: micro_fedora 
  nets:
  - oob_net 
  - name: ovs_1
    port_name: source
    nic: ovs_eth 
    ovs: true

sink_vm:
  profile: micro_fedora 
  nets:
  - oob_net 
  - name: ovs_2
    port_name: sink
    nic: ovs_eth 
    ovs: true
