---

vm_net:
 type: network
 cidr: 10.0.5.0/24

micro_fedora:
  type: profile
  image: Fedora-Cloud-Base-30-1.2.x86_64.qcow2
  memory: 512 
  numcpus: 1
  disks:
   - size: 5
  nets:
   - vm_net 
  pool: image_pool 

source_vm:
  profile: micro_fedora 

sink_vm:
  profile: micro_fedora 

local:
    type: kvm
    host: localhost
    pool: image_pool
