---
- name: Deploy|Provisioning of godon custom osuosl ci_runner
  hosts: all
  gather_facts: false 
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
  tasks:
      - name: setup custom ci runner
        import_role:
          name: ci_runner
