---
- name: Controller instrument to stage individual test run session 
  hosts: all
  gather_facts: false 
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
  tasks:
      - name: cleanup run containment 
        file:
          path: "{{ run_containment_dir }}"
          state: absent 
