---
#Copyright (c) 2019 Matthias Tafelmeier.
#
#This file is part of godon
#
#godon is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as
#published by the Free Software Foundation, either version 3 of the
#License, or (at your option) any later version.
#
#godon is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this godon. If not, see <http://www.gnu.org/licenses/>.

openapi: 3.0.0
info:
  version: 0.0.0
  title: godon control API
  description: API for controlling godon optimizer

servers:
  - url: /v0

paths:
  /breeders:
    get:
      description: Provides info on configured breeders
      responses:
        '200':
           description: Successfully returned list of configured breeders
           content:
             application/json:
               schema:
                 type: array
                 items:
                   type: object
                   required:
                     - id
                   properties:
                     id:
                       type: string
        '400':
           description: Invalid request
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string
    post:
      description: Create a breeder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
           description: Successfully created the breeder
        '400':
           description: Invalid request
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string
    put:
      description: Update a breeder configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
           description: Successfully updated the running breeder
        '400':
           description: Invalid request
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string

  /breeders/{id}:
    delete:
      description: Purge a breeder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
           description: Successfully purged the breeder
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string
        '400':
           description: Invalid request
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string
    get:
      description: Obtain information about breeder from its id(uuid)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
           description: Successfully returned list of configured breeders
           content:
             application/json:
               schema:
                 type: array
                 items:
                   type: object
                   required:
                     - id
                   properties:
                     id:
                       type: string
        '400':
           description: Invalid request
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   message:
                     type: string
