##
## Copyright (c) 2019 Matthias Tafelmeier.
##
## This file is part of godon
##
## godon is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, either version 3 of the
## License, or (at your option) any later version.
##
## godon is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this godon. If not, see <http://www.gnu.org/licenses/>.
##

on:
  pull_request:
    types: [ labeled ]
    branches:
      - master


jobs:
  test_perform:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tests')}}
    runs-on: [self-hosted, linux] # only unique osuosl instance
    env:
      MASK_FILE: testing/maskfile.md
    steps:
      - name: perform test run
        run: >
             source /etc/bashrc;
             cp testing/infra/credentials/ssh/id_rsa testing/infra/credentials/ssh/id_rsa_robot;
             chmod 0600 testing/infra/credentials/ssh/id_rsa_robot;

             mask --maskfile "${MASK_FILE}" testing perform;
