---

- name:
  hosts: all
  gather_facts: false
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
  tasks:
      - name: install ss exporter pkgs
        apt:
            name:
                - gcc
                - python3-dev
            state: present

      - name: deploy ss exporter
        script: ./deploy_ss_exporter.sh

      - name: setup recon prometheus server
        include_role:
            name: ansible-prometheus
        vars:
            prometheus_version: 2.19.2
            prometheus_web_listen_address: "0.0.0.0:9090"
            prometheus_global:
                scrape_interval: 5s
                scrape_timeout: 15s
            prometheus_scrape_configs:
                # ss exporter
                - job_name: ss2_flows
                  static_configs:
                      - targets:
                          - "localhost:9091"
                # sflow-rt exporter
                - job_name: sflow_flows
                  metrics_path: "/prometheus/metrics/ALL/ALL/txt"
                  static_configs:
                      - targets:
                          - "localhost:9092"
